export const weatherConditions = [
  "clear sky",
  "few clouds",
  "scattered clouds",
  "broken clouds",
  "shower rain",
  "rain",
  "thunderstorm",
  "snow",
  "mist",
  "smoke",
  "haze",
  "dust",
  "fog",
  "sand",
  "ash",
  "squall",
  "tornado",
  "overcast clouds",
  "cloudy",
  "partly cloudy",
  "mostly cloudy",
  "light rain",
  "showers",
  "light snow",
  "heavy snow",
  "sleet",
  "hail",
  "light shower snow",
  "shower snow",
  "heavy shower snow",
  "drizzle",
  "light intensity drizzle",
  "heavy intensity drizzle",
  "light intensity drizzle rain",
  "drizzle rain",
  "heavy intensity drizzle rain",
  "shower rain and drizzle",
  "heavy shower rain and drizzle",
  "shower drizzle",
  "light shower rain",
  "heavy shower rain",
  "ragged shower rain",
  "light intensity shower rain",
  "moderate rain",
  "very heavy rain",
  "extreme rain",
  "freezing rain",
  "light intensity shower rain",
  "heavy intensity shower rain",
  "ragged shower rain",
  "light snow",
  "snow",
  "heavy snow",
];

export const imageArray = [
  "clear-day",
  "extreme",
  "overcast",
  "overcast-day",
  "overcast-night",
  "partly-cloudy-day",
  "partly-cloudy-night",
  "starry-night",
  "dust-day",
  "dust-night",
  "dust-wind",
  "extreme-day-smoke",
  "extreme-night-smoke",
  "fog-day",
  "fog-night",
  "haze-day",
  "haze-night",
  "mist",
  "overcast-day-smoke",
  "overcast-night-smoke",
  "smoke-particles",
  "tornado",
  "drizzle",
  "extreme-day-drizzle",
  "extreme-day-rain",
  "extreme-drizzle",
  "extreme-night-drizzle",
  "extreme-night-rain",
  "extreme-rain",
  "overcast-day-drizzle",
  "overcast-day-rain",
  "overcast-day-sleet",
  "overcast-night-drizzle",
  "overcast-night-rain",
  "overcast-night-sleet",
  "overcast-rain",
  "partly-cloudy-day-rain",
  "partly-cloudy-night-rain",
  "rain",
  "raindrops",
  "extreme-day-hail",
  "extreme-day-sleet",
  "extreme-day-snow",
  "extreme-night-hail",
  "extreme-night-sleet",
  "extreme-night-snow",
  "overcast-day-hail",
  "overcast-day-sleet",
  "overcast-day-snow",
  "overcast-night-hail",
  "overcast-night-sleet",
  "overcast-night-snow",
  "snow",
  "thunderstorms-day",
  "thunderstorms-day-extreme",
  "thunderstorms-day-extreme-rain",
  "thunderstorms-day-overcast",
  "thunderstorms-day-overcast-rain",
  "thunderstorms-day-rain",
  "thunderstorms-day-snow",
  "thunderstorms-night",
  "thunderstorms-night-extreme",
  "thunderstorms-night-extreme-rain",
  "thunderstorms-night-extreme-snow",
  "thunderstorms-night-overcast",
  "thunderstorms-night-overcast-rain",
  "thunderstorms-night-overcast-snow",
  "thunderstorms-night-rain",
  "thunderstorms-night-snow",
];

export const city_names = [
  "Paris",
  "Rome",
  "Berlin",
  "Cairo",
  "Lisbon",
  "Sydney",
  "Seoul",
  "Prague",
  "Vienna",
  "Delhi",
  "Athens",
  "Oslo",
  "Hanoi",
  "Doha",
  "Sofia",
  "Minsk",
  "Amman",
  "Madrid",
  "Riyadh",
  "Tehran",
  "Osaka",
  "Seoul",
  "Lima",
  "Hanoi",
  "Nairobi",
  "Doha",
  "Sofia",
  "Minsk",
  "Amman",
  "Madrid",
  "Miami",
  "Dallas",
  "Tampa",
  "Paris",
  "Lima",
  "Cairo",
  "Rome",
  "Tokyo",
  "Boston",
  "Seoul",
];
// give 6 random city names from the city_names array

export const randomCityNames = [...new Set(city_names)]
  .sort(() => Math.random() - 0.5)
  .slice(0, 5);
